### ISSUE TITLE
Specs outline different names for same method

### ISSUE THREAD

**Issue by snickers495** [learn-co-curriculum/rails-pollywog-ranch#31]
Not understanding why certain specs passed and others didn't, I looked through them more closely and found the name for the same method changed between specs. In the router, it asked for 

"  # code your post to  '/tadpoles/:id/metamorphosize' here
  # it should direct to the tadpoles controller, the metamorphosize action"

Whereas in the instructions it asks for: 
"You'll add an action, #metamorphose, to this controller, config/routes.rb,
Here you'll allow a form to post to /tadpoles/:id/metamorphose
This should route the request to the TadpolesController's #metamorphose action"

Then, in the specs themselves, it would change between "metamorphose" and "metamorphosize", so I would have some specs pass and others not.

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback! The issue (duplicated in #33) has been resolved with a pull request. I will be doing a full review on the lab now to make sure the pull request addressed all inconsistencies.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
