### ISSUE TITLE
metamorphose/metamorphosize issue

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/rails-pollywog-ranch#33]
This lab needs some fixing - the tests and the instructions are confused between wanting metamorphose and metamorphosize

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue @baschenbrenner and providing the pull request @kwebster2!

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
