### ISSUE TITLE
Demo site doesn't work properly

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/rails-pollywog-ranch#4]
Except for the home screen, no images load on any pages. Like this:
<img width="912" alt="screen shot 2015-09-08 at 3 39 21 pm" src="https://cloud.githubusercontent.com/assets/12770108/9745438/ee7b64d2-563f-11e5-9df9-728458ae5f9e.png">

After clicking on a tadpole to view, this view came up:
<img width="590" alt="screen shot 2015-09-08 at 3 36 44 pm" src="https://cloud.githubusercontent.com/assets/12770108/9745457/0973c81a-5640-11e5-87fc-367aabff16ad.png">

**Comment by AnnJohn** [comment]
Thanks @garettarrowood as always for raising the issue. We'll put this one on icebox for now and "thaw" out when we get to reviewing the Rails portion of our track.

**Comment by ipc103** [comment]
going to remove the link to the demo until we can get it working properly
